[package]
name = "generate"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "generate"
path = "src/main.rs"

[dependencies]
core = { path = "../core" }
rand = { version = "0.8", features = ["std_rng"] }
serde_json = "1.0"